blogs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import never_cache

from blogs.apps import BlogsConfig
from blogs.views import (
    BlogListView,
    BlogDetailsView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogsConfig.name

urlpatterns = [
    path("posts/", BlogListView.as_view(), name="post_list"),
    path("post/<int:pk>/", BlogDetailsView.as_view(), name="post_detail"),
    path("post/create/", never_cache(BlogCreateView.as_view()), name="post_create"),
    path(
        "post/<int:pk>/update/",
        never_cache(BlogUpdateView.as_view()),
        name="post_update",
    ),
    path(
        "post/<int:pk>/delete/",
        never_cache(BlogDeleteView.as_view()),
        name="post_delete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blogs.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterUserView, email_verification, ChangePasswordView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterUserView.as_view(), name="register"),
    path("email_confirm/<str:token>/", email_verification, name="email_confirm"),
    path("reset_password/", ChangePasswordView.as_view(), name="reset_password"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="почта")
    photo = models.ImageField(
        upload_to="users/photo/",
        verbose_name="фото",
        blank=True,
        null=True,
        help_text="Добавьте свое фото",
    )
    phone = models.CharField(
        max_length=35,
        blank=True,
        null=True,
        verbose_name="телефон",
        help_text="Введите номер телефона",
    )
    country = models.CharField(
        max_length=35,
        blank=True,
        null=True,
        verbose_name="страна",
        help_text="Добавьте свою страну",
    )

    token = models.CharField(
        max_length=100, verbose_name="Токен", blank=True, null=True
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(label="Введите ваш email")

users/views.py
import secrets
import random
import string

from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, FormView
from django.contrib.auth.hashers import make_password

from users.forms import UserRegisterForm, PasswordResetRequestForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class RegisterUserView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email_confirm/{token}/"
        send_mail(
            subject="Подтверждение регистрации",
            message=f"Для подтверждения регистрации перейдите по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:login"))


class ChangePasswordView(FormView):
    template_name = "users/change_password.html"
    form_class = PasswordResetRequestForm
    success_url = reverse_lazy(
        "users:login"
    )  # URL куда перенаправить после успешного восстановления пароля

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        try:
            user = User.objects.get(email=email)
            new_password = "".join(
                random.choices(string.ascii_letters + string.digits, k=12)
            )
            user.password = make_password(new_password)
            user.save()
            send_mail(
                subject="Ваш новый пароль",
                message=f"Ваш новый пароль: {new_password}",
                from_email=EMAIL_HOST_USER,  # Замените на ваш email
                recipient_list=[user.email],
            )
        except User.DoesNotExist:
            form.add_error("email", "Пользователь с таким email не найден")
            return self.form_invalid(form)

        return super().form_valid(form)

users/templates/users/change_password.html
{% extends 'catalog/home.html' %}
{% block content %}
<div class="container">
    <h2>Восстановление пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
<!--<!doctype html>-->
{% extends 'catalog/home.html'%}
<!--{% load static %}-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Document</title>-->
<!--    <link rel="stylesheet" href="{% static 'css/style_link.css' %}">-->
<!--</head>-->
<!--<body>-->
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="mt-3">
                        <a href="{% url 'users:reset_password' %}" class="forgot-password-link">Забыли пароль?</a>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">
                    Войти
                </button>
            </div>
        </div>
    </form>
</div>
<!--</body>-->

<style>
.forgot-password-link {
    text-decoration: none;
    color: black;
}

.forgot-password-link:hover {
    color: blue;
}
</style>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/home.html'%}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Зарегистрироваться
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}