blogs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import never_cache

from blogs.apps import BlogsConfig
from blogs.views import (
    BlogListView,
    BlogDetailsView,
    BlogCreateView,
    BlogUpdateView,
    BlogDeleteView,
)

app_name = BlogsConfig.name

urlpatterns = [
    path("posts/", BlogListView.as_view(), name="post_list"),
    path("post/<int:pk>/", BlogDetailsView.as_view(), name="post_detail"),
    path("post/create/", never_cache(BlogCreateView.as_view()), name="post_create"),
    path(
        "post/<int:pk>/update/",
        never_cache(BlogUpdateView.as_view()),
        name="post_update",
    ),
    path(
        "post/<int:pk>/delete/",
        never_cache(BlogDeleteView.as_view()),
        name="post_delete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView,
    ContactsView,
    ProductDetailsView,
    ProductCreateView,
    ProductUpdateView,
    ProductByCategoryView,
    CategoryListView,
)

app_name = CatalogConfig.name


urlpatterns = [
    path("", ProductListView.as_view(), name="home"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path(
        "product/<int:pk>/",
        cache_page(60)(ProductDetailsView.as_view()),
        name="product_details",
    ),
    path(
        "product/create/",
        never_cache(ProductCreateView.as_view()),
        name="product_create",
    ),
    path(
        "product/update/<int:pk>/",
        never_cache(ProductUpdateView.as_view()),
        name="product_update",
    ),
    path(
        "products/category/<int:category_id>",
        ProductByCategoryView.as_view(),
        name="products_by_category",
    ),
    path("categories/", CategoryListView.as_view(), name="category_list"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blogs.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Категория", help_text="Введите категорию"
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Описание категории",
        help_text="Введите описание категории",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=100, verbose_name="Товар", help_text="Введите название товара"
    )
    description = models.TextField(
        blank=True,
        null=True,
        verbose_name="Описание товара",
        help_text="Введите описание товара",
    )
    image_product = models.ImageField(
        upload_to="catalog/media",
        blank=True,
        null=True,
        verbose_name="Изображение",
        help_text="Загрузите изображение товара",
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        help_text="Введите категорию",
        blank=True,
        null=True,
        related_name="catalog",
    )
    cost_product = models.IntegerField(
        verbose_name="Стоимость товара", help_text="Введите стоимость товара"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        help_text="Укажите владельца товара",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    is_published = models.BooleanField(default=False, verbose_name="Статус публикации")

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        permissions = [
            ("can_cancel_publish_product", "Can Cancel Publish Product"),
            ("can_change_description_product", "Can Change Description Product"),
            ("can_change_category_product", "Can Change Category Product"),
        ]

    def __str__(self):
        return self.name


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        related_name="versions",
        on_delete=models.CASCADE,
        verbose_name="Товар",
    )
    version_number = models.CharField(
        max_length=50, verbose_name="Номер версии", help_text="Введите номер версии"
    )
    version_name = models.CharField(
        max_length=255,
        verbose_name="Название версии",
        help_text="Введите название версии",
    )
    is_current = models.BooleanField(default=False, verbose_name="Активная версия")

    class Meta:
        verbose_name = "Версия товара"
        verbose_name_plural = "Версии товара"

    def __str__(self):
        return f"{self.product.name} - {self.version_name} ({self.version_number})"

catalog/forms.py
from django import forms
from django.forms import BooleanField

from catalog.models import Product, Version

FORBIDDEN_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


def clean(cleaned_data):
    for word in FORBIDDEN_WORDS:
        if word in cleaned_data.lower():
            raise forms.ValidationError(f"Название не может содержать слово: {word}")
    return cleaned_data


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "description", "image_product", "cost_product", "category")

    def clean_name(self):
        cleaned_data = self.cleaned_data.get("name")
        clean(cleaned_data)

    def clean_description(self):
        cleaned_data = self.cleaned_data.get("description")
        clean(cleaned_data)


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ("description", "category", "is_published")

    def clean_name(self):
        cleaned_data = self.cleaned_data.get("name")
        clean(cleaned_data)

    def clean_description(self):
        cleaned_data = self.cleaned_data.get("description")
        clean(cleaned_data)


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    TemplateView,
    DetailView,
    CreateView,
    UpdateView,
)

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version, Category
from catalog.services import get_cached_categories


class ContactsView(TemplateView):
    template_name = "catalog/contacts.html"

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")

        print(f"name: {name}, phone: {phone}, message: {message}")

        return render(request, self.template_name)


class ProductListView(ListView):
    model = Product
    context_object_name = "products"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = context["products"]
        context["categories"] = Category.objects.all()

        for product in products:
            current_version = product.versions.filter(is_current=True).first()
            if current_version:
                product.current_version = {
                    "version_number": current_version.version_number,
                    "version_name": current_version.version_name,
                }
            else:
                product.current_version = None

        return context


class ProductDetailsView(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFromset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = VersionFromset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = VersionFromset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = super().get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return super().render_to_response(
                self.get_context_data(form=form, formset=formset)
            )
        product = form.save()
        user = self.request.user
        product.user = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_details")

    def get_success_url(self):
        return reverse("catalog:product_details", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFromset = inlineformset_factory(Product, Version, VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = VersionFromset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = VersionFromset(instance=self.object)
        return context_data

    def get_form_class(self):
        user = self.request.user
        if user == self.object.user:
            return ProductForm
        elif (
            user.has_perm("product.can_cancel_publish_product")
            and user.has_perm("product.can_change_description_product")
            and user.has_perm("product.can_change_category_product")
        ):
            return ProductModeratorForm
        else:
            raise PermissionDenied

    def form_valid(self, form):
        context_data = super().get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return super().render_to_response(
                self.get_context_data(form=form, formset=formset)
            )


class ProductByCategoryView(ListView):
    model = Product
    template_name = "catalog/products_by_category.html"
    context_object_name = "products_by_category"

    def get_queryset(self):
        category_id = self.kwargs.get("category_id")
        return Product.objects.filter(category_id=category_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.get(id=self.kwargs.get("category_id"))
        context["categories"] = Category.objects.all()
        return context


class CategoryListView(ListView):
    model = Category
    context_object_name = "categories"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()

        return context

    def get_queryset(self):
        return get_cached_categories()

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/home.html'%}
{% block content %}
<body>
    <h1>Хотите удалить пост?</h1>
    <form class='row' method="post">
        {% csrf_token %}
        <button type="submit">
            Удалить
        </button>
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:post_list'%}" role="button">Отмена</a>
    </form>
</body>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends "catalog/home.html" %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
        {% for blog in object_list %}
            {% if blog.published%}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{{ blog.preview | media_filter }}">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ blog.title }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ blog.content | truncatechars:100 }}</li>
                    </ul>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:post_detail' blog.pk %}" role="button">Подробнее</a>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:post_update' blog.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:post_delete' blog.pk %}" role="button">Удалить</a>
                </div>
            </div>
        </div>
    {% endif %}
        {% endfor %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:post_create'%}">Создать новый пост</a>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends "catalog/home.html" %}
{% block content %}
<div class="row text-center">
    {% for category in object_list %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products_by_category' category.id %}">{{ category.name }}</a>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазин электроники</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% include 'catalog/includes/inc_menu.html'  %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% include 'catalog/includes/inc_footer.html' %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Магазин электроники</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{% include 'catalog/includes/inc_menu.html'  %}



<div class="container">
    {% block content %}
    {% endblock %}

    {% include 'catalog/includes/inc_footer.html' %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_detail.html
{% extends "catalog/home.html" %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{{ object.image_product | media_filter }}" alt="">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.name }}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.description }}</li>
                    </ul>
                    <a class="btn btn-lg btn-block btn-outline-primary" href="#" role="button">Купить</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/home.html'%}
{% block content %}
<h2>{% if form.instance.pk %}Редактировать{% else %}Создать{% endif %} продукт</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <h3>Версии</h3>
    {{ formset.management_form }}
    {% for form in formset.forms %}
    {{ form.as_p }}
    {% endfor %}

    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends "catalog/home.html" %}
{% load my_tags %}
{% block content %}
<div class="row text-center">
    {% for product in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <img src="{{ product.image_product | media_filter }}">
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {% if product.current_version %}
                    <p><strong>Текущая версия:</strong> {{ product.current_version.version_name }} ({{ product.current_version.version_number }})</p>
                    {% else %}
                    <p><strong>Текущая версия:</strong> Нет активной версии</p>
                    {% endif %}
                    <li>{{ product.description | truncatechars:100 }}</li>
                </ul>
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'catalog:product_details' product.pk %}" role="button">Подробнее</a>
                {% if product.user == request.user or user.is_superuser or request.user|is_moderator %}
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                {% endif %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="#" role="button">Купить</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_create'%}">Создать новый товар</a>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/products_by_category.html
{% extends "catalog/home.html" %}
{% load my_tags %}
{% block content %}
  <h2>Товары в категории {{ category.name }}</h2>
  <div class="row text-center">
    {% for product in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <img src="{{ product.image_product | media_filter }}">
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    {% if product.current_version %}
                    <p><strong>Текущая версия:</strong> {{ product.current_version.version_name }} ({{ product.current_version.version_number }})</p>
                    {% else %}
                    <p><strong>Текущая версия:</strong> Нет активной версии</p>
                    {% endif %}
                    <li>{{ product.description | truncatechars:100 }}</li>
                </ul>
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'catalog:product_details' product.pk %}" role="button">Подробнее</a>
                {% if product.user == request.user or user.is_superuser or request.user|is_moderator %}
                <a class="btn btn-lg btn-block btn-outline-primary"
                   href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                {% endif %}
                <a class="btn btn-lg btn-block btn-outline-primary" href="#" role="button">Купить</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% if user.is_authenticated %}
    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_create'%}">Создать новый товар</a>
    {% endif %}
  </div>
{% endblock %}